title: Albert Casadessús
email: myname.mysurname@gmail.com
description: >- # this means to ignore newlines until "next item:"
  I am a Software Engineer, interested in building high performing teams, clean code and promote KISS.

twitter_username: acasadessus
github_username: llissssss
linkedin_username: albertcasadessus

# Build settings
theme: minima
plugins:
  - jekyll-feed

google_analytics: UA-31485368-1
show_excerpts: true

include:
  - _pages

# Minima: custom header links
header_pages:
  - _pages/about.md
  - _pages/blog.md